Add ToString methods
Sbrebbaz/ProgettoCodex pull request #10
Opened 2024-05-10 16:45 UTC by uortizrodas1

2024-05-11 12:41 UTC, Sbrebbaz requested changes
Un paio di correzioni necessarie 😊
Sarebbe anche carino se ci fossero un po di `\n` in modo da non creare righe troppo lunghe
e per le matrici magari riuscire a vedere la loro posizione relativa ex:
![image](https://github.com/Sbrebbaz/ProgettoCodex/assets/50167869/0c44a4c0-2b42-4b72-90e4-aa1166348158)

Facci sapere se hai dubbi

2024-05-11 12:41 UTC, Sbrebbaz commented on src/base/Deck.java
La richiesta era di stampare il numero di carte rimanenti,
basterebbe fare `deck.Size`

2024-05-11 12:41 UTC, Sbrebbaz commented on src/base/Table.java
Look good but non penso sia necessario stampare le constanti

2024-05-11 12:41 UTC, Sbrebbaz commented on src/base/Player.java
La richiesta era di fare il metodo `ToString` che stampa `id`,`name`,`points`
E un altro metodo che chiameterei `ToStringPlayerHand` che richiama il `ToString` sopra e aggiunge il hand come hai fatto tu

2024-05-11 12:41 UTC, Sbrebbaz commented on src/base/Map.java
> +		return "Map{" +
La richiesta era stampare la lista delle carte piazzate con le coordinate di quella carta

Non servono le grandezze della matrice o la submap

Inoltre stampare una matrice con `Arrays.toString` ti stampa i puntatori dei singoli array

2024-05-11 12:41 UTC, Sbrebbaz commented on src/base/Card.java
> +	public String toString() {
Servirebbe fare il `ToString` del `Side` non del indice del `Side`
`side[visibleSide]`

2024-05-11 12:41 UTC, Sbrebbaz commented on src/base/GenericSide.java
Non e' necessario, lo erediterebbe comunque da `Side`

2024-05-11 12:41 UTC, Sbrebbaz commented on src/base/PointResourceRequirementSide.java
Manca il `ToString` di `super`

2024-05-11 12:41 UTC, Sbrebbaz commented on src/base/PointCornerRequirementSide.java
Aggiungi il nome della classe perche' tanto il requisito degli angoli e' sempre e solo di coprirli
Cosi sistemiamo anche la issue #9

2024-05-11 12:41 UTC, Sbrebbaz commented on src/base/PointPositionRequirementSide.java
Stesso problema di `Map` non puoi fare `Arrays.toString` di una matrice

2024-05-11 12:44 UTC, Dantillio requested changes
sono d'accordo con quello scritto da @Sbrebbaz

2024-05-16 17:18 UTC, Sbrebbaz approved these changes

2024-05-16 17:19 UTC, merged